### ISSUE TITLE
Move Object Folder

### ISSUE THREAD

**Issue by han44-illinois** [engrit-illinois/New-CMOrgModelDeploymentCollection#2]
The readme states this cannot be done with powershell, but apparently it can. I just did it with the following lines:

```
Prep-MECM
$CMCollection = Get-CMDeviceCollection -Name "UIUC-ENGR-IS Deploy Siemens Simcenter Flotherm 2210 (Required)"
Move-CMObject -InputObject $CMCollection -FolderPath "MP0:\DeviceCollection\UIUC-ENGR\Instructional\Deployment Collections\Software\Installs"
```

It's not documented properly on [MSFT's documentation](https://learn.microsoft.com/en-us/powershell/module/configurationmanager/move-cmobject?view=sccm-ps) (they only list that it's possible for stuff in the Software Library tab) but this random blog post indicates this can also be used on Device Collections: https://blog.ctglobalservices.com/powershell/kaj/how-to-move-objects-in-configuration-manager-admin-console/

If you have time to work this in, that'd be awesome. If not, I don't mind contributing these few lines myself.

**Comment by mmseng** [comment]
I actually stumbled across `Move-CMObject` not too long ago as well and still have a tab open, but hadn't gotten around to trying it out yet. https://learn.microsoft.com/en-us/powershell/module/configurationmanager/move-cmobject?view=sccm-ps

TBH though I'm not really sure what I would do with it except add an additional parameter to let you specify where you want to move the collection(s) after creation, since there's not necessarily a "standard" location to put them. But I guess even that _could_ be slightly more convenient than manually moving the objects.

**Comment by han44-illinois** [comment]
Yeah, I linked your first link in my initial post. Looking at it again, I realize I was only looking at the `-InputObject` flag when reading the documentation, which led me to believe it didn't apply to Device Collections until I stumbled across that blog post...

I do think some logic can be built in, at least based on the $App string. For example:

```
# If the $App string contains "UIUC-ENGR", then put it in the ENGR Apps folder
if($App -like "*UIUC-ENGR*"){
    $FolderPath = "MP0:\DeviceCollection\UIUC-ENGR\.Org shared collections\Deployments\ENGR Apps"
}else{
    $FolderPath = "MP0:\DeviceCollection\UIUC-ENGR\.Org shared collections\Deployments\Campus Apps"
}
```
And maybe a separate condition for if the $ISOnly switch is toggled.

It would probably be more robust to query the folder path for where the Application is stored and base the condition on that, but I want to say this should probably work too

We treat the Adobe apps specially so I don't think this script would cover those regardless.

**Comment by mmseng** [comment]
I updated the readme to be more accurate and reference this issue for now.

I know the readme suggests 2 "appropriate" locations, depending on IS-only or not, but, as you say, other factors may mean that the app is better suited to go in a different folder (campus vs. ENGR, adobe vs. not, etc.). I'd personally rather not force a particular folder which could be inappropriate, as that kind of asking for some apps to get left in weird places.

I don't mind adding a new parameter like I mentioned earlier though, and it could accept keywords for common locations, or there could be other parameters which default the location to certain places based on some arbitrary logic. That way you still have to intentionally decide where it's going, but don't necessarily have to type out/copy-paste a full path.

**Comment by mmseng** [comment]
More or less resolved in https://github.com/engrit-illinois/New-CMOrgModelDeploymentCollection/commit/a8f53a3c7a19c46c530cbffe02385192b9bd623c, which adds the `-MoveCollectionsToFolder` and `-CollectionsFolder` parameters. See the readme for details.
