### ISSUE TITLE
Feature request: display the created CollectionID in the script output

### ISSUE THREAD

**Issue by han44-illinois** [engrit-illinois/New-CMOrgModelDeploymentCollection#5]
This is really minor but would make this script slightly easier to use for people already using other mecm powershell cmdlets.

In its current state, what I do after creating a new cmorg collection is store that collection in a variable by copying its name e.g. `$Collection = Get-CMDeviceCollection -Name "asldifjalsdij"`

This works, but because the generated collection names tend to be pretty long, I need to use a mouse to copy that collection name for this cmdlet. Alternatively, I can either find the collection manually in the MECM console to find the ID or type out the collection name and hope I don't make any mistakes. Neither of these is really ideal.

If the CollectionID were displayed somewhere, it would save me this one small step and allow use of this script to not require any mouse usage or the above workarounds.

**Comment by mmseng** [comment]
Resolved in https://github.com/engrit-illinois/New-CMOrgModelDeploymentCollection/commit/e2711b4e69563e2a90c182e603f0304fc5372cfa

![image](https://user-images.githubusercontent.com/8218085/221950823-bac123d5-4806-4b39-a079-9a4fa87d4be9.png)
